/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TabCalaulation;

import javax.swing.table.DefaultTableModel;

public class adminPage extends javax.swing.JFrame {

    /**
     * Creates new form score
     */
    tournament tour = new tournament();
    public adminPage() {
        i=0;
        initComponents();
    }
    
    //User
    public String user[][] = new String[4][2];
    public int i;
    public DefaultTableModel model;
    public void createUser(){
        model = (DefaultTableModel) table.getModel();
        if(i<1){
            user[i][0] = userField.getText().toString();
            user[i][1] = passField.getPassword().toString();
            model.addRow(user[0]);
            i++;
        }
    }
    //User
    
    //setScoreRules
    public scoreRules scoreRule = new scoreRules();
    public Double max_margin, max_reply, max_speaker, min_reply, mini_speaker, reply_step, score_step;
    public void setScoreRules(scoreRules score){
        if(score.max_margin.equals("") && score.max_reply_FIeld.equals("") && score.max_speaker.equals("") && score.min_reply.equals("") && score.mini_speaker.equals("") && score.reply_step.equals("") && score.score_step.equals("")){}
        else{
            scoreRule=score;
            String temp;
            scoreRule.max_margin = 0;
            temp = scoreRule.max_reply_FIeld.toString();
            scoreRule.max_reply = Integer.parseInt(temp);
            temp = scoreRule.max_speaker_FIeld.toString();
            scoreRule.max_speaker = Integer.parseInt(temp);
            temp = scoreRule.min_reply_FIeld.toString();
            scoreRule.min_reply = Integer.parseInt(temp);
            temp = scoreRule.mini_speaker_FIeld.toString();
            scoreRule.mini_speaker = Integer.parseInt(temp);
            temp = scoreRule.reply_step_FIeld.toString();
            scoreRule.reply_step = Integer.parseInt(temp);
            temp = scoreRule.score_step_FIeld.toString();
            scoreRule.score_step = Integer.parseInt(temp);
        }
    }
    //setScoreRules
    
    //DataEntryRules
    public dataEntryRule dataEntry;
    void setDataEntryRules(dataEntryRule rule){
        dataEntry = rule;
    }
    //DataEntryRules
    
    //debateRules
    debateRules debateRule;
    void setDebateRule(debateRules rule){debateRule=rule;}
    //debateRules
    
    //drawRules
    drawRules drawRule;
    void setDrawRule(drawRules rule){drawRule=rule;}
    //drawRules 
    
    //standingsRule
    standingsRule standingRule;
    void setStandingRule(standingsRule rule){standingRule=rule;}
    //standingsRule
    
    //addTeam
    addTeam team;
    void setAddTeam(addTeam t){team=t;}
    //addTeam
    
    //addAdjudicator
    addAdjudicator adjudicator;
    void setAddAdjudicator(addAdjudicator a){adjudicator=a;}
    //addAdjudicator
    
    //addVenue
    addVenue venue;
    void setAddVenue(addVenue v){venue=v;}
    //addVenue
    
    //checkIn
    checkin check;
    void setCheckIn(checkin c){check=c;}
    //checkIn
    
    //roundCheckin
    roundCheckin roundCheck[] = new roundCheckin[6];
    void setRoundCheckIn(roundCheckin r, Integer i){roundCheck[i]=r;}
    //roundCheckin
    
    //roundDraw
    roundDraw draw[] = new roundDraw[6];
    void setRoundDraw(roundDraw r, Integer i){draw[i]=r;}
    //roundDraw
    
    //roundResult
    roundResult roundresult[] = new roundResult[6];
    void setRoundResult(roundResult r, Integer i){roundresult[i]=r;}
    //roundResult
    
    //Tournament data
    public String Tournament_name, Tournament_user, Tournament_pass;
    public Double Tournament_round, Tournament_break;
    
    void setTour(tournament tour){
    
        Tournament_name = tour.tournament_tname.getText().toString();
        String number = tour.tournament_roundNumber.getText().toString();
        Tournament_round = Double.parseDouble(number);
        Tournament_break = 8.0;
        Tournament_user = tour.tournament_adminUsername.getText().toString();
        Tournament_pass = tour.tournament_adminPass.getPassword().toString();
        System.out.println("user: "+Tournament_user+"\nPass: "+Tournament_pass);
    }
    //Tournament data

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        createBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        debateRuleBtn = new javax.swing.JMenuItem();
        drawRulesbtn = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        standingRuleBtn = new javax.swing.JMenuItem();
        dataEntryBtn = new javax.swing.JMenuItem();
        checkInBtn = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        addTeamBtn = new javax.swing.JMenuItem();
        addAdjBtn = new javax.swing.JMenuItem();
        addVenueBtn = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        standingsTeamBtn = new javax.swing.JMenuItem();
        standingsSpeakerBtn = new javax.swing.JMenuItem();
        standingsReplySpeakerBtn = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        checkIn0 = new javax.swing.JMenuItem();
        drawBtn0 = new javax.swing.JMenuItem();
        result0 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        checkIn1 = new javax.swing.JMenuItem();
        drawBtn1 = new javax.swing.JMenuItem();
        result1 = new javax.swing.JMenuItem();
        roundBtn2 = new javax.swing.JMenu();
        checkIn2 = new javax.swing.JMenuItem();
        drawBtn2 = new javax.swing.JMenuItem();
        result2 = new javax.swing.JMenuItem();
        roundBtn3 = new javax.swing.JMenu();
        checkIn3 = new javax.swing.JMenuItem();
        drawBtn3 = new javax.swing.JMenuItem();
        result3 = new javax.swing.JMenuItem();
        QF = new javax.swing.JMenu();
        checkInQF = new javax.swing.JMenuItem();
        drawBtnQF = new javax.swing.JMenuItem();
        resultQF = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        checkInSF = new javax.swing.JMenuItem();
        drawBtnSF = new javax.swing.JMenuItem();
        resultSF = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        checkInF = new javax.swing.JMenuItem();
        drawBtnF = new javax.swing.JMenuItem();
        resultF = new javax.swing.JMenuItem();
        creditBtn = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Debate Tabulation Software");
        setBackground(new java.awt.Color(204, 204, 179));
        setName("frame"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 179));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));

        jLabel1.setBackground(new java.awt.Color(204, 204, 179));
        jLabel1.setFont(new java.awt.Font("Roboto Slab ExtraBold", 1, 24)); // NOI18N
        jLabel1.setText("User");

        userField.setFont(new java.awt.Font("Quicksand", 1, 15)); // NOI18N
        userField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userField.setToolTipText("");
        userField.setBorder(null);

        jLabel4.setBackground(new java.awt.Color(204, 204, 179));
        jLabel4.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel4.setText("Password");
        jLabel4.setToolTipText("");

        createBtn.setBackground(new java.awt.Color(0, 0, 0));
        createBtn.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        createBtn.setForeground(new java.awt.Color(255, 255, 255));
        createBtn.setText("Create");
        createBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createBtn.setBorderPainted(false);
        createBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createBtn.setDoubleBuffered(true);
        createBtn.setOpaque(false);
        createBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createBtnMouseClicked(evt);
            }
        });
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(204, 204, 179));
        jLabel5.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel5.setText("Username");
        jLabel5.setToolTipText("");

        passField.setFont(new java.awt.Font("Quicksand", 1, 15)); // NOI18N
        passField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passField.setBorder(null);

        table.setAutoCreateRowSorter(true);
        table.setFont(new java.awt.Font("Quicksand Light", 0, 11)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table.setEnabled(false);
        table.setShowGrid(true);
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 184, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(101, 101, 101)
                        .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(98, 98, 98)
                        .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(93, 93, 93)
                .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(513, 513, 513)
                .addComponent(jLabel1)
                .addGap(409, 409, 409))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(469, 30));

        jMenu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        jMenu1.setText("SetUp");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        debateRuleBtn.setText("Debate Rules");
        debateRuleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        debateRuleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debateRuleBtnActionPerformed(evt);
            }
        });
        jMenu1.add(debateRuleBtn);

        drawRulesbtn.setText("Draw Rules");
        drawRulesbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        drawRulesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawRulesbtnActionPerformed(evt);
            }
        });
        jMenu1.add(drawRulesbtn);

        jMenuItem9.setText("Score Rules");
        jMenuItem9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem9MouseClicked(evt);
            }
        });
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        standingRuleBtn.setText("Standings Rules");
        standingRuleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        standingRuleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standingRuleBtnActionPerformed(evt);
            }
        });
        jMenu1.add(standingRuleBtn);

        dataEntryBtn.setText("Data Entry");
        dataEntryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataEntryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataEntryBtnActionPerformed(evt);
            }
        });
        jMenu1.add(dataEntryBtn);

        checkInBtn.setText("Check-In");
        checkInBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInBtnActionPerformed(evt);
            }
        });
        jMenu1.add(checkInBtn);

        jMenuBar1.add(jMenu1);

        jMenu4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu4.setText("Add");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        addTeamBtn.setText("Team");
        addTeamBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addTeamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeamBtnActionPerformed(evt);
            }
        });
        jMenu4.add(addTeamBtn);

        addAdjBtn.setText("Adjudicator");
        addAdjBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addAdjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdjBtnActionPerformed(evt);
            }
        });
        jMenu4.add(addAdjBtn);

        addVenueBtn.setText("Venue");
        addVenueBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addVenueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVenueBtnActionPerformed(evt);
            }
        });
        jMenu4.add(addVenueBtn);

        jMenuBar1.add(jMenu4);

        jMenu5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu5.setText("Standings");
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        standingsTeamBtn.setText("Team");
        standingsTeamBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        standingsTeamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standingsTeamBtnActionPerformed(evt);
            }
        });
        jMenu5.add(standingsTeamBtn);

        standingsSpeakerBtn.setText("Speaker");
        standingsSpeakerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        standingsSpeakerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standingsSpeakerBtnActionPerformed(evt);
            }
        });
        jMenu5.add(standingsSpeakerBtn);

        standingsReplySpeakerBtn.setText("Reply-Speaker");
        standingsReplySpeakerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        standingsReplySpeakerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standingsReplySpeakerBtnActionPerformed(evt);
            }
        });
        jMenu5.add(standingsReplySpeakerBtn);

        jMenuBar1.add(jMenu5);

        jMenu6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu6.setText("Round 1");
        jMenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        checkIn0.setText("Check-In");
        checkIn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkIn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkIn0ActionPerformed(evt);
            }
        });
        jMenu6.add(checkIn0);

        drawBtn0.setText("Draw");
        drawBtn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        drawBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawBtn0ActionPerformed(evt);
            }
        });
        jMenu6.add(drawBtn0);

        result0.setText("Result");
        result0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        result0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                result0ActionPerformed(evt);
            }
        });
        jMenu6.add(result0);

        jMenuBar1.add(jMenu6);

        jMenu7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu7.setText("Round 2");
        jMenu7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        checkIn1.setText("Check-In");
        checkIn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkIn1ActionPerformed(evt);
            }
        });
        jMenu7.add(checkIn1);

        drawBtn1.setText("Draw");
        drawBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        drawBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawBtn1ActionPerformed(evt);
            }
        });
        jMenu7.add(drawBtn1);

        result1.setText("Result");
        result1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        result1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                result1ActionPerformed(evt);
            }
        });
        jMenu7.add(result1);

        jMenuBar1.add(jMenu7);

        roundBtn2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        roundBtn2.setText("Round 3");
        roundBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        roundBtn2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        checkIn2.setText("Check-In");
        checkIn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkIn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkIn2ActionPerformed(evt);
            }
        });
        roundBtn2.add(checkIn2);

        drawBtn2.setText("Draw");
        drawBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        drawBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawBtn2ActionPerformed(evt);
            }
        });
        roundBtn2.add(drawBtn2);

        result2.setText("Result");
        result2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        result2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                result2ActionPerformed(evt);
            }
        });
        roundBtn2.add(result2);

        jMenuBar1.add(roundBtn2);

        roundBtn3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        roundBtn3.setText("Round 4");
        roundBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        roundBtn3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        checkIn3.setText("Check-In");
        checkIn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkIn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkIn3ActionPerformed(evt);
            }
        });
        roundBtn3.add(checkIn3);

        drawBtn3.setText("Draw");
        drawBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        drawBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawBtn3ActionPerformed(evt);
            }
        });
        roundBtn3.add(drawBtn3);

        result3.setText("Result");
        result3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        result3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                result3ActionPerformed(evt);
            }
        });
        roundBtn3.add(result3);

        jMenuBar1.add(roundBtn3);

        QF.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        QF.setText("QF");
        QF.setToolTipText("Quarterfinals");
        QF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QF.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        checkInQF.setText("Check-In");
        checkInQF.setToolTipText("");
        checkInQF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkInQF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInQFActionPerformed(evt);
            }
        });
        QF.add(checkInQF);

        drawBtnQF.setText("Draw");
        drawBtnQF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        drawBtnQF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawBtnQFActionPerformed(evt);
            }
        });
        QF.add(drawBtnQF);

        resultQF.setText("Result");
        resultQF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resultQF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultQFActionPerformed(evt);
            }
        });
        QF.add(resultQF);

        jMenuBar1.add(QF);

        jMenu10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu10.setText("SF");
        jMenu10.setToolTipText("Semifinals");
        jMenu10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        checkInSF.setText("Check-In");
        checkInSF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkInSF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInSFActionPerformed(evt);
            }
        });
        jMenu10.add(checkInSF);

        drawBtnSF.setText("Draw");
        drawBtnSF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        drawBtnSF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawBtnSFActionPerformed(evt);
            }
        });
        jMenu10.add(drawBtnSF);

        resultSF.setText("Result");
        resultSF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resultSF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultSFActionPerformed(evt);
            }
        });
        jMenu10.add(resultSF);

        jMenuBar1.add(jMenu10);

        jMenu11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu11.setText("Final");
        jMenu11.setToolTipText("Final");
        jMenu11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        checkInF.setText("Check-In");
        checkInF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkInF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInFActionPerformed(evt);
            }
        });
        jMenu11.add(checkInF);

        drawBtnF.setText("Draw");
        drawBtnF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        drawBtnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawBtnFActionPerformed(evt);
            }
        });
        jMenu11.add(drawBtnF);

        resultF.setText("Result");
        resultF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resultF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultFActionPerformed(evt);
            }
        });
        jMenu11.add(resultF);

        jMenuBar1.add(jMenu11);

        creditBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        creditBtn.setText("Credit");
        creditBtn.setToolTipText("");
        creditBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        creditBtn.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        creditBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditBtnMouseClicked(evt);
            }
        });
        creditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditBtnActionPerformed(evt);
            }
        });
        jMenuBar1.add(creditBtn);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleParent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleDescription("Score Rules");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createBtnActionPerformed

    private void createBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createBtnMouseClicked
        // TODO add your handling code here:
        createUser();
    }//GEN-LAST:event_createBtnMouseClicked

    private void jMenuItem9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem9MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem9MouseClicked

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        scoreRules score = new scoreRules();
        score.setVisible(true);
        score.setAdmin(this);
        this.dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void dataEntryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataEntryBtnActionPerformed
        // TODO add your handling code here:
        dataEntryRule rule = new dataEntryRule();
        rule.setVisible(true);
        rule.setAdmin(this);
        this.dispose();
    }//GEN-LAST:event_dataEntryBtnActionPerformed

    private void debateRuleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debateRuleBtnActionPerformed
        // TODO add your handling code here:
        debateRules rule = new debateRules();
        rule.setVisible(true);
        rule.setAdmin(this);
        this.dispose();
    }//GEN-LAST:event_debateRuleBtnActionPerformed

    private void drawRulesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawRulesbtnActionPerformed
        // TODO add your handling code here:
        drawRules rule = new drawRules();
        rule.setVisible(true);
        rule.setAdmin(this);
        this.dispose();
    }//GEN-LAST:event_drawRulesbtnActionPerformed

    private void standingRuleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standingRuleBtnActionPerformed
        // TODO add your handling code here: 
        standingsRule rule = new standingsRule();
        rule.setVisible(true);
        rule.setAdmin(this);
        this.dispose();
    }//GEN-LAST:event_standingRuleBtnActionPerformed

    private void checkInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInBtnActionPerformed
        // TODO add your handling code here:
        checkin check = new checkin();
        check.setVisible(true);
        check.setAdmin(this);
        this.dispose();
    }//GEN-LAST:event_checkInBtnActionPerformed

    private void addTeamBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeamBtnActionPerformed
        // TODO add your handling code here:
        addTeam team = new addTeam();
        team.setVisible(true);
        team.setAdmin(this);
    }//GEN-LAST:event_addTeamBtnActionPerformed

    private void addAdjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdjBtnActionPerformed
        // TODO add your handling code here:
        addAdjudicator adj = new addAdjudicator();
        adj.setVisible(true);
        adj.setAdmin(this);
        this.dispose();
    }//GEN-LAST:event_addAdjBtnActionPerformed

    private void addVenueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVenueBtnActionPerformed
        // TODO add your handling code here:
        addVenue venue = new addVenue();
        venue.setVisible(true);
        venue.setAdmin(this);
        this.dispose();
    }//GEN-LAST:event_addVenueBtnActionPerformed

    private void standingsTeamBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standingsTeamBtnActionPerformed
        // TODO add your handling code here:
        standingsTeam team = new standingsTeam();
        team.setVisible(true);
        team.setAdmin(this);
    }//GEN-LAST:event_standingsTeamBtnActionPerformed

    private void standingsSpeakerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standingsSpeakerBtnActionPerformed
        // TODO add your handling code here:
        standingsSpeaker speaker = new standingsSpeaker();
        speaker.setVisible(true);
        speaker.setAdmin(this);
    }//GEN-LAST:event_standingsSpeakerBtnActionPerformed

    private void standingsReplySpeakerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standingsReplySpeakerBtnActionPerformed
        // TODO add your handling code here:
        standingsReplySpeaker reply = new standingsReplySpeaker();
        reply.setVisible(true);
        reply.setAdmin(this);
    }//GEN-LAST:event_standingsReplySpeakerBtnActionPerformed

    //checkinBtnPrformed
    void checkinBtnPrformed(Integer i){
        roundCheckin check = new roundCheckin();
        check.setVisible(true);
        check.setAdmin(this, i);
    }
    //checkinBtnPrformed
    
    private void checkIn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkIn0ActionPerformed
        // TODO add your handling code here:
        checkinBtnPrformed(0);
    }//GEN-LAST:event_checkIn0ActionPerformed
    
    //checkinBtnPrformed
    void drawBtnPrformed(Integer i){
        roundDraw draw = new roundDraw();
        draw.setVisible(true);
        draw.setAdmin(this, 0);
    }
    //checkinBtnPrformed
    
    private void drawBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawBtn0ActionPerformed
        // TODO add your handling code here:
        drawBtnPrformed(0);
    }//GEN-LAST:event_drawBtn0ActionPerformed
    
    //checkinBtnPrformed
    void resultBtnPrformed(Integer i){
        roundCheckin check = new roundCheckin();
        check.setVisible(true);
        check.setAdmin(this, i);
    }
    //checkinBtnPrformed
    
    private void result0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result0ActionPerformed
        // TODO add your handling code here:
        resultBtnPrformed(0);
    }//GEN-LAST:event_result0ActionPerformed

    private void checkIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkIn1ActionPerformed
        // TODO add your handling code here:
        checkinBtnPrformed(1);
    }//GEN-LAST:event_checkIn1ActionPerformed

    private void drawBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawBtn1ActionPerformed
        // TODO add your handling code here:
        drawBtnPrformed(1);
    }//GEN-LAST:event_drawBtn1ActionPerformed

    private void result1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result1ActionPerformed
        // TODO add your handling code here:
        resultBtnPrformed(1);
    }//GEN-LAST:event_result1ActionPerformed

    private void checkIn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkIn2ActionPerformed
        // TODO add your handling code here:
        checkinBtnPrformed(2);
    }//GEN-LAST:event_checkIn2ActionPerformed

    private void drawBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawBtn2ActionPerformed
        // TODO add your handling code here:
        drawBtnPrformed(2);
    }//GEN-LAST:event_drawBtn2ActionPerformed

    private void result2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result2ActionPerformed
        // TODO add your handling code here:
        resultBtnPrformed(2);
    }//GEN-LAST:event_result2ActionPerformed

    private void checkIn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkIn3ActionPerformed
        // TODO add your handling code here:
        checkinBtnPrformed(3);
    }//GEN-LAST:event_checkIn3ActionPerformed

    private void drawBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawBtn3ActionPerformed
        // TODO add your handling code here:
        drawBtnPrformed(3);
    }//GEN-LAST:event_drawBtn3ActionPerformed

    private void result3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result3ActionPerformed
        // TODO add your handling code here:
        resultBtnPrformed(3);
    }//GEN-LAST:event_result3ActionPerformed

    private void checkInQFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInQFActionPerformed
        // TODO add your handling code here:
        checkinBtnPrformed(4);
    }//GEN-LAST:event_checkInQFActionPerformed

    private void drawBtnQFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawBtnQFActionPerformed
        // TODO add your handling code here:
        drawBtnPrformed(4);
    }//GEN-LAST:event_drawBtnQFActionPerformed

    private void resultQFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultQFActionPerformed
        // TODO add your handling code here:
        resultBtnPrformed(4);
    }//GEN-LAST:event_resultQFActionPerformed

    private void checkInSFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInSFActionPerformed
        // TODO add your handling code here:
        checkinBtnPrformed(5);
    }//GEN-LAST:event_checkInSFActionPerformed

    private void drawBtnSFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawBtnSFActionPerformed
        // TODO add your handling code here:
        drawBtnPrformed(5);
    }//GEN-LAST:event_drawBtnSFActionPerformed

    private void resultSFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultSFActionPerformed
        // TODO add your handling code here:
        resultBtnPrformed(5);
    }//GEN-LAST:event_resultSFActionPerformed

    private void checkInFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInFActionPerformed
        // TODO add your handling code here:
        checkinBtnPrformed(6);
    }//GEN-LAST:event_checkInFActionPerformed

    private void drawBtnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawBtnFActionPerformed
        // TODO add your handling code here:
        drawBtnPrformed(6);
    }//GEN-LAST:event_drawBtnFActionPerformed

    private void resultFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultFActionPerformed
        // TODO add your handling code here:
        resultBtnPrformed(6);
    }//GEN-LAST:event_resultFActionPerformed

    private void creditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditBtnActionPerformed

    private void creditBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditBtnMouseClicked
        // TODO add your handling code here:
        credit obj = new credit();
        obj.setVisible(true);
    }//GEN-LAST:event_creditBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu QF;
    private javax.swing.JMenuItem addAdjBtn;
    private javax.swing.JMenuItem addTeamBtn;
    private javax.swing.JMenuItem addVenueBtn;
    private javax.swing.JMenuItem checkIn0;
    private javax.swing.JMenuItem checkIn1;
    private javax.swing.JMenuItem checkIn2;
    private javax.swing.JMenuItem checkIn3;
    private javax.swing.JMenuItem checkInBtn;
    private javax.swing.JMenuItem checkInF;
    private javax.swing.JMenuItem checkInQF;
    private javax.swing.JMenuItem checkInSF;
    private javax.swing.JButton createBtn;
    private javax.swing.JMenu creditBtn;
    private javax.swing.JMenuItem dataEntryBtn;
    private javax.swing.JMenuItem debateRuleBtn;
    private javax.swing.JMenuItem drawBtn0;
    private javax.swing.JMenuItem drawBtn1;
    private javax.swing.JMenuItem drawBtn2;
    private javax.swing.JMenuItem drawBtn3;
    private javax.swing.JMenuItem drawBtnF;
    private javax.swing.JMenuItem drawBtnQF;
    private javax.swing.JMenuItem drawBtnSF;
    private javax.swing.JMenuItem drawRulesbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JPasswordField passField;
    private javax.swing.JMenuItem result0;
    private javax.swing.JMenuItem result1;
    private javax.swing.JMenuItem result2;
    private javax.swing.JMenuItem result3;
    private javax.swing.JMenuItem resultF;
    private javax.swing.JMenuItem resultQF;
    private javax.swing.JMenuItem resultSF;
    private javax.swing.JMenu roundBtn2;
    private javax.swing.JMenu roundBtn3;
    private javax.swing.JMenuItem standingRuleBtn;
    private javax.swing.JMenuItem standingsReplySpeakerBtn;
    private javax.swing.JMenuItem standingsSpeakerBtn;
    private javax.swing.JMenuItem standingsTeamBtn;
    protected javax.swing.JTable table;
    protected javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
