/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TabCalaulation;

public class titlePage extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public titlePage() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePage_Panel = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        titlePage_addButton = new javax.swing.JLabel();
        loginButton = new javax.swing.JLabel();
        voteButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Debate Tabulation Software");
        setBackground(new java.awt.Color(204, 204, 179));
        setName("frame"); // NOI18N
        setResizable(false);

        titlePage_Panel.setBackground(new java.awt.Color(204, 204, 179));
        titlePage_Panel.setPreferredSize(new java.awt.Dimension(1080, 720));

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/header.png"))); // NOI18N

        titlePage_addButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlePage_addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        titlePage_addButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        titlePage_addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titlePage_addButtonMouseClicked(evt);
            }
        });

        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/people.png"))); // NOI18N
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        voteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vote.png"))); // NOI18N
        voteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout titlePage_PanelLayout = new javax.swing.GroupLayout(titlePage_Panel);
        titlePage_Panel.setLayout(titlePage_PanelLayout);
        titlePage_PanelLayout.setHorizontalGroup(
            titlePage_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePage_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(header)
                .addGap(185, 185, 185))
            .addGroup(titlePage_PanelLayout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(titlePage_addButton)
                .addGap(171, 171, 171)
                .addComponent(loginButton)
                .addGap(171, 171, 171)
                .addComponent(voteButton)
                .addContainerGap(274, Short.MAX_VALUE))
        );
        titlePage_PanelLayout.setVerticalGroup(
            titlePage_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePage_PanelLayout.createSequentialGroup()
                .addComponent(header)
                .addGap(120, 120, 120)
                .addGroup(titlePage_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlePage_addButton)
                    .addComponent(loginButton)
                    .addComponent(voteButton))
                .addGap(0, 136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePage_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        titlePage_Panel.getAccessibleContext().setAccessibleName("Debate Tabulation Software");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void titlePage_addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePage_addButtonMouseClicked
        // TODO add your handling code here:
        tournament tour = new tournament();
        this.dispose();
        tour.setVisible(true);
        tour.setTitlePage(this);
    }//GEN-LAST:event_titlePage_addButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(titlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(titlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(titlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(titlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        //titlePage title = new titlePage();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new titlePage().setVisible(true);
            }
        });
    }
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel header;
    private javax.swing.JLabel loginButton;
    private javax.swing.JPanel titlePage_Panel;
    public javax.swing.JLabel titlePage_addButton;
    private javax.swing.JLabel voteButton;
    // End of variables declaration//GEN-END:variables
    
}
